# Gruvbox Dark syntax highlighting for zsh-syntax-highlighting

ZSH_HIGHLIGHT_STYLES[default]='fg=#ebdbb2'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#fb4934,bold'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#fb4934'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#b8bb26'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#b8bb26'
ZSH_HIGHLIGHT_STYLES[function]='fg=#b8bb26'
ZSH_HIGHLIGHT_STYLES[command]='fg=#b8bb26'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#fabd2f,italic'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#fb4934'
ZSH_HIGHLIGHT_STYLES[path]='fg=#83a598'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#83a598,underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#d3869b'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#d3869b'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#fabd2f'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#fabd2f'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#b8bb26'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#b8bb26'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#b8bb26'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#fabd2f'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#8ec07c'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#ebdbb2'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#fb4934,bold'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#928374,italic'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=#8ec07c'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=#d3869b'
